### ISSUE TITLE
Apply the foldl' patch from head.hackage

### ISSUE THREAD

**Issue by Mikolaj** [Mikolaj/enummapset#21]
The patch is here: https://gitlab.haskell.org/ghc/head.hackage/-/blob/master/patches/enummapset-0.7.1.0.patch?ref_type=heads

@TeofilC, is this supposed to be a clean fix or a quick-fix that only works for GHC 9.12 and newer?

**Comment by TeofilC** [comment]
Thanks for following up on this! I think this should be a clean fix. Though it will mean older GHCs get a warning for hiding a non-existent import. If you'd prefer to avoid that, I'd be happy to write up a patch that uses a qualified import to get foldl' instead

**Comment by Mikolaj** [comment]
Yay, that's very generous of you. Full discolsure, though: this library is much less used than it should be. :) So your effort will not have as huge an impact as it should have. On the other hand, this is a high-level library for people that want their code to be cleaner, easier to read and safer, so having it emit warnings (I wonder if it does currently?) is a bit iffy. Your call. :)

**Comment by TeofilC** [comment]
I was just about to implement this, but to my surprise the library already builds with GHC HEAD.

It turns out this was already done with this MR: https://github.com/Mikolaj/enummapset/pull/20
I think the head.hackage patch only exists because there hasn't been a release since then.

It did make me realise that the deepseq bound needs to be relaxed so I'll make an MR for that.

**Comment by Mikolaj** [comment]
Oh, I see! To my defence, this was 5 months ago. :)

Would you suggest a release after the deepseq bound bump or is it relevant only for HEAD users for now?

**Comment by TeofilC** [comment]
> Oh, I see! To my defence, this was 5 months ago. :)

Indeed! No harm done in any case

> Would you suggest a release after the deepseq bound bump or is it relevant only for HEAD users for now?

deepseq-1.5 seems to be included in GHC 9.8.1, so a release at some point would be good, but no rush. It's early days still

https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/libraries/version-history#:~:text=deepseq-,1.5.0.0,-1.4.8.1

**Comment by Mikolaj** [comment]
Released: https://hackage.haskell.org/package/enummapset-0.7.2.0

I guess the head.hackage patch is now spurious?

**Comment by TeofilC** [comment]
Thanks! Yes I think it can be safely removed now

**Comment by TeofilC** [comment]
Head.hackage MR: https://gitlab.haskell.org/ghc/head.hackage/-/merge_requests/342

**Comment by Mikolaj** [comment]
Thanks again. Closing.
